# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZegoEffectsExampleLegacy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZegoEffectsExampleLegacy
  pod 'ZegoExpressEngine'
  pod 'YTKNetwork'
  pod 'YYModel'
  pod 'Masonry'
#  pod 'MBProgressHUD'

end
